### PR TITLE
Aslan Branch

### PR DESCRIPTION
**Pull request by AslanElviraElza**
Take a look at it

### CODE REVIEW

**Review by emine-celik — APPROVED** [review]
Looks good

**Review by suguz06 — APPROVED** [review]

**Review by emine-celik — APPROVED** [review]
Looks good

**Review by suguz06 — APPROVED** [review]

**Review by suguz06 — APPROVED** [review]

**Comment by arhmcolak92** [comment]
Looks great

**Review by arhmcolak92 — APPROVED** [review]
Looks great

**Pull request merged**
